version: '3'

services: 
    nginx:
      image: nginx
      volumes:
        - ./Conf/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./Conf/cert.pem:/etc/ssl/server.pem:ro
        - ./Conf/key.pem:/etc/ssl/server.key:ro
      ports: 
        - "444:443"
    grpc-server:
      build: .
      environment: 
        ASPNETCORE_URLS: http://*:5000
      volumes:
        - ./RPedretti.Grpc.Server/data/movies.db:/app/data/movies.db:rw